apiVersion: batch/v1
kind: CronJob
metadata:
  name: game-folder-cleaner-cronjob
  namespace: game-folder-cleaner
spec:
  schedule: "0 2 * * *" # Ogni giorno alle 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleaner
              image: filippogrande/game-folder-cleaner:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: cleaner-config
                - secretRef:
                    name: telegram-secret
              volumeMounts:
                - name: games-data
                  mountPath: /data
          volumes:
            - name: games-data
              hostPath:
                path: /mnt/games
                type: Directory
