apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
  namespace: game-folder-cleaner
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "" # Inserire il token o creare via kubectl set
  TELEGRAM_CHAT_ID: ""
